Inventory/urls.py
from django.urls import path

from Inventory import views

app_name = 'inventory'

urlpatterns = [
    path('', views.index, name="index"),
    path('logging_in/', views.logging_in, name='logging_in'),
    path('logging_out/', views.logging_out, name="logging_out"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('dashboard/summary/', views.summary_tables, name='summary'),
    path('dashboard/summary/export_csv', views.export_csv, name="export_to_csv"),
    path('dashboard/inventory/', views.inventory, name='inventory'),
    path('dashboard/inventory/condura', views.inventory_condura, name="inventory_condura"),
    path('dashboard/inventory/carrier', views.inventory_carrier, name="inventory_carrier"),
    path('dashboard/inventory/kelvinator', views.inventory_kelvinator, name="inventory_kelvinator"),
    path('dashboard/inventory/edit_stocks', views.stocks, name="edit_stocks"),
    path('dashboard/inventory/edit_stocks/search_item', views.search_item, name="search_item"),
    path('dashboard/inventory/edit_stocks/get_stock', views.get_stock, name="get_stock"),
    path('dashboard/inventory/edit_stocks/update', views.update, name="update"),
]

RMC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Inventory.urls')),
    path('admin/', admin.site.urls),
]

Inventory/models.py
from django.db import models

# Create your models here.


class ModelType(models.Model):
    type = models.CharField(max_length=15)

    def __str__(self):
        return str(self.type)

class AirconType(models.Model):
    aircon_type = models.CharField(max_length=25)


    def __str__(self):
        return str(self.aircon_type)

class Aircon(models.Model):
    model_type = models.ForeignKey(ModelType, on_delete=models.DO_NOTHING)
    aircon_type = models.ForeignKey(AirconType, on_delete=models.DO_NOTHING)
    stocks = models.IntegerField()
    model_number = models.CharField(max_length=255)

    def __str__(self):
        return str(self.model_type)

    def __str__(self):
        return str(self.aircon_type)

Summary/models.py
from django.db import models

# Create your models here.

Inventory/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.contrib.auth.models import User
from django.urls import reverse
from .models import Aircon
from .resources import AirconResource

# Create your views here.


def index(request):
    return render(request, 'Inventory/index.html')



def logging_in(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    auth = User.objects.get(username=username)
    user = authenticate(request, username=username, password=password)
    request.session['user'] = username

    context = {
        'users': auth
    }

    if user is not None:
        login(request, user)
        if auth.is_superuser:
            return HttpResponseRedirect(reverse('inventory:dashboard'))
        else:
            return HttpResponseRedirect(reverse('inventory:index'))
    else:
        return render(request, 'Inventory/index.html', {})


def summary_tables(request):
    username = request.session['user']
    user = User.objects.get(username=username)
    aircon = Aircon.objects.all()
    context = {
        'users': user,
        'aircon': aircon
    }
    return render(request, 'Inventory/tables.html', context)


def dashboard(request):
    username = request.session['user']
    user = User.objects.get(username=username)
    context = {
        'users': user
    }
    return render(request, 'Inventory/dashboard.html', context)


def inventory(request):

    username = request.session['user']
    user = User.objects.get(username=username)
    condura_stock_wrac = Aircon.objects.get(model_number = 'WCONX008EA2')
    condura_stock_hw = Aircon.objects.get(model_number = '13-42KCR018')
    condura_stock_pe = Aircon.objects.get(model_number = 'FP-53CCA024313')
    carrier_stock_wrac = Aircon.objects.get(model_number = 'WCARG006EE')
    carrier_stock_hw = Aircon.objects.get(model_number = 'FP-42CVUR016-703')
    carrier_stock_pe = Aircon.objects.get(model_number = 'FB-53CCF-LDS024308')
    kelvinator_stock_wrac = Aircon.objects.get(model_number = 'WKELW010EC')
    context = {
        'users': user,
        'condura_wrac': condura_stock_wrac,
        'condura_hw': condura_stock_hw,
        'condura_pe':condura_stock_pe,
        'carrier_wrac': carrier_stock_wrac,
        'carrier_hw': carrier_stock_hw,
        'carrier_pe': carrier_stock_pe,
        'kelvinator_wrac': kelvinator_stock_wrac
    }
    return render(request, 'Inventory/inventory.html', context)

def inventory_carrier(request):

    username = request.session['user']
    user = User.objects.get(username=username)
    carrier_stock_wrac = Aircon.objects.get(model_number = 'WCARG006EE')
    carrier_stock_hw = Aircon.objects.get(model_number = 'FP-42CVUR016-703')
    carrier_stock_pe = Aircon.objects.get(model_number = 'FB-53CCF-LDS024308')
    context = {
        'users': user,
        'carrier_wrac': carrier_stock_wrac,
        'carrier_hw': carrier_stock_hw,
        'carrier_pe': carrier_stock_pe
    }
    return render(request, 'Inventory/inventory_carrier.html', context)

def inventory_condura(request):

    username = request.session['user']
    user = User.objects.get(username=username)
    condura_stock_wrac = Aircon.objects.get(model_number = 'WCONX008EA2')
    condura_stock_hw = Aircon.objects.get(model_number = '13-42KCR018')
    condura_stock_pe = Aircon.objects.get(model_number = 'FP-53CCA024313')
    context = {
        'users': user,
        'condura_wrac': condura_stock_wrac,
        'condura_hw': condura_stock_hw,
        'condura_pe':condura_stock_pe,
    }
    return render(request, 'Inventory/inventory_condura.html', context)

def inventory_kelvinator(request):

    username = request.session['user']
    user = User.objects.get(username=username)
    kelvinator_stock_wrac = Aircon.objects.get(model_number = 'WKELW010EC')
    context = {
        'users': user,
        'kelvinator_wrac': kelvinator_stock_wrac
    }
    return render(request, 'Inventory/inventory_kelvinator.html', context)


def stocks(request):
    username = request.session['user']
    user = User.objects.get(username=username)
    aircon = Aircon.objects.all()
    condura_stock_wrac = Aircon.objects.get(model_number = 'WCONX008EA2')
    condura_stock_hw = Aircon.objects.get(model_number = '13-42KCR018')
    condura_stock_pe = Aircon.objects.get(model_number = 'FP-53CCA024313')
    carrier_stock_wrac = Aircon.objects.get(model_number = 'WCARG006EE')
    carrier_stock_hw = Aircon.objects.get(model_number = 'FP-42CVUR016-703')
    carrier_stock_pe = Aircon.objects.get(model_number = 'FB-53CCF-LDS024308')
    kelvinator_stock_wrac = Aircon.objects.get(model_number = 'WKELW010EC')
    context = {
        'users': user,
        'aircon': aircon,
        'condura_wrac': condura_stock_wrac,
        'condura_hw': condura_stock_hw,
        'condura_pe':condura_stock_pe,
        'carrier_wrac': carrier_stock_wrac,
        'carrier_hw': carrier_stock_hw,
        'carrier_pe': carrier_stock_pe,
        'kelvinator_wrac': kelvinator_stock_wrac
    }
    return render(request, 'Inventory/edit_stocks.html', context)


def search_item(request):
    model_number = request.POST.get('select_model_number')
    print(model_number)

    return render(request, 'Inventory/edit_stocks.html')


def get_stock(request):
    model_number = request.POST.get('model_number')
    print(model_number)
    aircon = Aircon.objects.get(model_number=model_number)
    stocks = aircon.stocks
    data = {
        "stocks": stocks
    }
    return JsonResponse(data)


def update(request):
    model_number = request.POST.get('model_number')
    stock = request.POST.get('stock')
    aircon = Aircon.objects.get(model_number=model_number)
    aircon.stocks = stock
    aircon.save()
    data = {
        "status": "success"
    }
    return JsonResponse(data)

def export_csv(request):
    aircon_resources = AirconResource()
    dataset = aircon_resources.export()
    response = HttpResponse(dataset.csv, content_type='application/json')
    response['Content-Disposition'] = 'attachment; filename="Aircon_Inventory.csv"'
    return response


def logging_out(request):
    del request.session['user']
    logout(request)
    return HttpResponseRedirect(reverse('inventory:index'))

Summary/views.py
from django.shortcuts import render

# Create your views here.

Inventory/templates/Inventory/dashboard.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Welcome To | RCM</title>
    <!-- Favicon-->
    <link rel="icon" href="../../static/Inventory/imgs/login-logo.png" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static 'Inventory/css/bootstrap.css'%}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static 'Inventory/css/waves.css'%}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static 'Inventory/css/animate.css'%}" rel="stylesheet" />

    <!-- Morris Chart Css-->
    <link href="{% static 'Inventory/css/morris.css'%}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{% static 'Inventory/css/dash_style.css'%}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{% static 'Inventory/css/all-themes.css'%}" rel="stylesheet" />
</head>

<body class="theme-red">
    <!-- Page Loader
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Please wait...</p>
        </div>
    </div> -->
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <!-- <div class="overlay"></div> -->
    <!-- #END# Overlay For Sidebars -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="{% url 'inventory:dashboard' %}">RCM - Inventory System</a>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image">
                    <img src="../../static/Inventory/imgs/user.png" width="48" height="48" alt="User" />
                </div>
                <div class="info-container">
                    <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ users.first_name }} {{ users.last_name}}</div>
                    <div class="email">{{ users.email }}</div>
                    <div class="btn-group user-helper-dropdown">
                        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="{% url 'inventory:logging_out' %}"><i class="material-icons">input</i>Sign Out</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="active">
                        <a href="{% url 'inventory:dashboard'%}">
                            <i class="material-icons">home</i>
                            <span>Home</span>
                        </a>
                    </li>
                    <li=>
                        <a href="{% url 'inventory:inventory'%}">
                            <i class="material-icons">assignment</i>
                            <span>Inventory</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'inventory:summary' %}">
                            <i class="material-icons">view_list</i>
                            <span>Tables</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; 2019 <a href="javascript:void(0);">RCM - Inventory</a>.
                </div>
                <div class="version">
                    <b>Version: </b> 1.0.0
                </div>
            </div>
            <!-- #Footer -->
        </aside>
        <!-- #END# Left Sidebar -->
        <!-- Right Sidebar -->
        <!-- #END# Right Sidebar -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>

            <!-- CPU Usage -->
            <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                      <h1 class="display-4">Welcome Back, Mr. {{ users.last_name}}</h1>
                      <p>Date Today is: <span id="datetime"></span></p>
                    </div>
                  </div>
            <!-- #END# CPU Usage -->
            <div class="row clearfix">
                <!-- Visitors -->
                <canvas id="myChart" width="10" height="3"></canvas>
                <!-- #END# Visitors -->
                <!-- Latest Social Trends -->
                <canvas id="myChart1" width="10" height="3"></canvas>
                <!-- #END# Latest Social Trends -->
                <!-- Answered Tickets -->
                <canvas id="myChart2" width="10" height="3"></canvas>
                <!-- #END# Answered Tickets -->
            </div>

        </div>
    </section>

    <!-- Jquery Core Js -->
    <script src="{% static 'Inventory/js/jquery.min.js'%}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static 'Inventory/js/bootstrap.js'%}"></script>

    <!-- Select Plugin Js -->
    <script src="{% static 'Inventory/js/bootstrap-select.js'%}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{% static 'Inventory/js/jquery.slimscroll.js'%}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{% static 'Inventory/js/waves.js'%}"></script>

    <!-- Jquery CountTo Plugin Js -->
    <script src="{% static 'Inventory/js/jquery.countTo.js'%}"></script>

    <!-- Morris Plugin Js -->
    <script src="{% static 'Inventory/js/raphael.min.js'%}"></script>
    <script src="{% static 'Inventory/js/morris.js'%}"></script>

    <!-- ChartJs -->
    <script src="{% static 'Inventory/js/Chart.bundle.js'%}"></script>

    <!-- Flot Charts Plugin Js -->
    <script src="{% static 'Inventory/js/jquery.flot.js'%}"></script>
    <script src="{% static 'Inventory/js/jquery.flot.resize.js'%}"></script>
    <script src="{% static 'Inventory/js/jquery.flot.pie.js'%}"></script>
    <script src="{% static 'Inventory/js/jquery.flot.catergories.js'%}"></script>
    <script src="{% static 'Inventory/js/jquery.flot.time.js'%}"></script>

    <!-- Sparkline Chart Plugin Js -->
    <script src="{% static 'Inventory/js/jquery.sparkline.js'%}"></script>

    <!-- Custom Js -->
    <script src="{% static 'Inventory/js/admin.js'%}"></script>
    <script src="{% static 'Inventory/js/index.js'%}"></script>

    <!-- Demo Js -->
    <script src="{% static 'Inventory/js/demo.js'%}"></script>
    <script>
            var dt = new Date();
            document.getElementById("datetime").innerHTML = (("0"+dt.getDate()).slice(-2)) +"."+ (("0"+(dt.getMonth()+1)).slice(-2)) +"."+ (dt.getFullYear()) +" "+ (("0"+dt.getHours()).slice(-2)) +":"+ (("0"+dt.getMinutes()).slice(-2));
            </script>
    <script src="{% static 'Inventory/js/chart.js' %}"></script>
</body>

</html>

Inventory/templates/Inventory/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
	{% load static %}
  <meta charset="UTF-8">
  <title>RCM</title>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
	<link rel='stylesheet' href="{% static 'Inventory/css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="../../static/Inventory/css/style.css">
	<link rel="icon" href="../../static/Inventory/imgs/login-logo.png" type="image/x-icon">
</head>
<body>
<!-- partial:index.partial.html -->

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>RCM INVENTORY</title>
</head>
<body>
	<!-- Main Content -->
	<div class="container-fluid">
		<div class="row main-content bg-success text-center">
			<div class="col-md-4 text-center company__info">
				<span class="company__logo"><h2><img src="../../static/Inventory/imgs/login-logo.png" alt="RCM-LOGO" height="150" width="150"></span>
				<h4 class="company_title">RCM INVENTORY</h4>
			</div>
			<div class="col-md-8 col-xs-12 col-sm-12 login_form ">
				<div class="container-fluid">
					<div class="row">
						<h2>Log In</h2>
					</div>
					<div class="row">
						<form method='POST' action="{% url 'inventory:logging_in' %}" control="" class="form-group">
							{% csrf_token %}
							<div class="row">
								<input type="text" name="username" id="username" class="form__input" placeholder="Username">
							</div>
							<div class="row">
								<!-- <span class="fa fa-lock"></span> -->
								<input type="password" name="password" id="password" class="form__input" placeholder="Password">
							</div>
							<div class="row">
								<input type="submit" value="Submit" class="btn">
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
<!-- partial -->
  
</body>
</html>